In [1]:
import numpy as np

In [2]:
np.random.seed(1)

In [3]:
vec1 = np.array([0, 0, 0])
mat1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [4]:
sample_for_class1 = np.random.multivariate_normal(vec1, mat1, 20).T

In [5]:
sample_for_class1


array([[ 1.62434536, -1.07296862,  1.74481176, -0.24937038, -0.3224172 ,
        -1.09989127,  0.04221375,  1.14472371,  0.90085595, -0.93576943,
        -0.69166075, -0.84520564, -1.11731035,  0.74204416, -0.74715829,
        -0.63699565,  0.12015895, -0.35224985, -0.20889423,  0.93110208],
       [-0.61175641,  0.86540763, -0.7612069 ,  1.46210794, -0.38405435,
        -0.17242821,  0.58281521,  0.90159072, -0.68372786, -0.26788808,
        -0.39675353, -0.67124613,  0.2344157 , -0.19183555,  1.6924546 ,
         0.19091548,  0.61720311, -1.1425182 ,  0.58662319,  0.28558733],
       [-0.52817175, -2.3015387 ,  0.3190391 , -2.06014071,  1.13376944,
        -0.87785842, -1.10061918,  0.50249434, -0.12289023,  0.53035547,
        -0.6871727 , -0.0126646 ,  1.65980218, -0.88762896,  0.05080775,
         2.10025514,  0.30017032, -0.34934272,  0.83898341,  0.88514116]])

In [6]:
sample_for_class1.shape

(3, 20)

In [7]:
assert sample_for_class1.shape == (3,20)

In [8]:
vec2 = np.array([1, 1, 1])
mat2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
sample_for_class2 = np.random.multivariate_normal(vec2, mat2, 20).T

In [9]:
sample_for_class2

array([[ 0.24560206,  0.70190716,  2.13162939, -0.39649634,  1.16003707,
        -1.02220122,  1.23009474,  0.79924193,  1.19829972,  1.37756379,
         2.19891788,  0.36126959,  0.65614632,  1.69803203,  1.40349164,
         1.16938243,  0.73378149,  1.31515939,  1.35054598, -0.61577235],
       [ 2.25286816,  1.48851815,  2.51981682, -0.44411381,  1.87616892,
         0.69379599,  1.76201118,  1.18656139,  1.11900865,  1.12182127,
         1.18515642,  1.42349435,  1.04359686,  0.55287144,  1.59357852,
         1.74055645,  1.03261455,  1.84616065, -0.31228341,  2.12141771],
       [ 1.51292982,  0.92442829,  3.18557541,  0.49553414,  1.31563495,
         1.82797464,  0.77767186,  1.41005165,  0.32933771,  2.12948391,
         0.62471505,  1.07734007,  0.37999916,  2.2245077 , -0.09491185,
         0.0462994 , -0.37311732,  0.14048406,  0.96130449,  1.40890054]])

In [10]:
sample_for_class2.shape

(3, 20)

In [11]:
all_data = np.concatenate((sample_for_class1, sample_for_class2), axis=1)

In [12]:
all_data.shape

(3, 40)

In [13]:
all_data

array([[ 1.62434536, -1.07296862,  1.74481176, -0.24937038, -0.3224172 ,
        -1.09989127,  0.04221375,  1.14472371,  0.90085595, -0.93576943,
        -0.69166075, -0.84520564, -1.11731035,  0.74204416, -0.74715829,
        -0.63699565,  0.12015895, -0.35224985, -0.20889423,  0.93110208,
         0.24560206,  0.70190716,  2.13162939, -0.39649634,  1.16003707,
        -1.02220122,  1.23009474,  0.79924193,  1.19829972,  1.37756379,
         2.19891788,  0.36126959,  0.65614632,  1.69803203,  1.40349164,
         1.16938243,  0.73378149,  1.31515939,  1.35054598, -0.61577235],
       [-0.61175641,  0.86540763, -0.7612069 ,  1.46210794, -0.38405435,
        -0.17242821,  0.58281521,  0.90159072, -0.68372786, -0.26788808,
        -0.39675353, -0.67124613,  0.2344157 , -0.19183555,  1.6924546 ,
         0.19091548,  0.61720311, -1.1425182 ,  0.58662319,  0.28558733,
         2.25286816,  1.48851815,  2.51981682, -0.44411381,  1.87616892,
         0.69379599,  1.76201118,  1.18656139,  1.

In [14]:
mean_dim1 = np.mean(all_data[0, :])
mean_dim2 = np.mean(all_data[1, :])
mean_dim3 = np.mean(all_data[2, :])

mean_vector = np.array([[mean_dim1], [mean_dim2], [mean_dim3]])

print('The Mean Vector:\n', mean_vector)

The Mean Vector:
 [[0.41667492]
 [0.69848315]
 [0.49242335]]


In [15]:
(all_data[:,1].reshape(3,1)).shape

(3, 1)

In [16]:
scatter_matrix = np.zeros((3,3))
for i in range(all_data.shape[1]):
    scatter_matrix += np.dot((all_data[:, i].reshape(3, 1) - mean_vector),(all_data[:, i].reshape(3, 1) - mean_vector).T)
print('The Scatter Matrix is :\n', scatter_matrix)

The Scatter Matrix is :
 [[38.4878051  10.50787213 11.13746016]
 [10.50787213 36.23651274 11.96598642]
 [11.13746016 11.96598642 49.73596619]]


In [17]:
eig_val, eig_vec = np.linalg.eig(scatter_matrix)

In [18]:
eig_val

array([65.16936779, 32.69471296, 26.59620328])

In [19]:
eig_vec

array([[-0.49210223, -0.64670286,  0.58276136],
       [-0.47927902, -0.35756937, -0.8015209 ],
       [-0.72672348,  0.67373552,  0.13399043]])

In [20]:
for ev in eig_vec:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))

In [22]:
eig_pairs = []
for i in range(len(eig_val)):
    eig_pairs += [(np.abs(eig_val[i]), eig_vec[:,i])]


In [23]:
eig_pairs

[(65.16936779078195, array([-0.49210223, -0.47927902, -0.72672348])),
 (32.69471296321796, array([-0.64670286, -0.35756937,  0.67373552])),
 (26.596203282097097, array([ 0.58276136, -0.8015209 ,  0.13399043]))]

In [24]:
eig_pairs.sort(key=lambda x: x[0], reverse=True)

In [25]:
eig_pairs

[(65.16936779078195, array([-0.49210223, -0.47927902, -0.72672348])),
 (32.69471296321796, array([-0.64670286, -0.35756937,  0.67373552])),
 (26.596203282097097, array([ 0.58276136, -0.8015209 ,  0.13399043]))]

In [26]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(3,1), eig_pairs[1][1].reshape(3,1)))
print('Matrix W:\n', matrix_w)

Matrix W:
 [[-0.49210223 -0.64670286]
 [-0.47927902 -0.35756937]
 [-0.72672348  0.67373552]]


In [30]:
transformed = np.dot(matrix_w.T,all_data)

In [31]:
transformed

array([[-0.12230714,  1.78582073, -0.72564846,  0.91911067, -0.48120545,
         1.26186049,  0.49974121, -1.36060904, -0.02630959,  0.20346559,
         1.02990798,  0.74684543, -0.76873682,  0.37184198, -0.48040292,
        -1.30433953, -0.57308381,  0.9748035 , -0.78806782, -1.23832629,
        -2.30009539, -1.73062935, -4.57170736,  0.04785487, -2.42616804,
        -1.15792646, -2.01497976, -1.98672036, -1.36534078, -2.76311357,
        -2.1041081 , -1.64296088, -1.09921946, -2.71718701, -1.38545546,
        -1.44331476, -0.58485289, -1.63411201, -1.21353834, -1.73760916],
       [-1.18757151, -1.16617976, -0.64124251, -1.74952646,  1.10969495,
         0.18151348, -0.97722286, -0.72412904, -0.42090149,  1.05827266,
         0.12619324,  0.77808138,  1.75701561, -1.00931473, -0.08774954,
         1.75869787, -0.09616466,  0.4009659 ,  0.49058694, -0.10791262,
         0.05492635, -0.3633537 , -0.13330484,  0.74907576, -0.53466984,
         1.6445517 , -0.90160187,  0.00885182, -0.

In [32]:
transformed.shape

(2, 40)